[package]
name = "ray-tracing-in-one-weekend"
version = "0.1.0"
authors = ["王子恒 <wangziheng03@meituan.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"